in: | 
    {{ $posts := datasource "posts" | data.ToJSON  }}
    {{ $posts = $posts | data.JSONArray }}
    {{ range $i, $e := $posts }}
      {{ $file := $e.title | strings.Slug }}
      {{ tmpl.Exec "postT" . | file.Write (print "content/posts/" $file ".md") }}
    {{ end }}

templates:
  - postT=gomplate/api.tmpl
      
datasources:
  posts:
    url: https://jsonplaceholder.typicode.com/posts?type=application/array+json


suppressEmpty: true
outputFiles:
  - api
