baseURL = "https://quizzical-wozniak-468938.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"

[module]

[[module.imports]]
  path = "github.com/pointyfar/base-hugo-theme"
  disable = false